name: Sequent Workflow

on:
  pull_request:
    branches:
      - main
      - artifacts
      - artifacts_2
      - artifacts_3
      
jobs:
  build-debug:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'

      - name: Restore dependencies
        run: | 
          dotnet restore TestDrivers9/TestDrivers9.csproj
          dotnet restore UnitTest_L10/UnitTest_L10.csproj
          dotnet restore ClassMassiv8/ClassMassiv8.csproj

      - name: Build project
        run: dotnet build TestDrivers9/TestDrivers9.csproj --configuration Debug

  build-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'

      - name: Restore dependencies
        run: |
          dotnet restore TestDrivers9/TestDrivers9.csproj
          dotnet restore UnitTest_L10/UnitTest_L10.csproj
          dotnet restore ClassMassiv8/ClassMassiv8.csproj
        
      - name: Build project
        run: dotnet build TestDrivers9/TestDrivers9.csproj --configuration Release
    
  testing-configurations:
    runs-on: ubuntu-latest
    strategy:
        matrix:
            configuration: [Debug, Release]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
            dotnet version: '7.0.x'
        
      - name: Run tests
        run: dotnet test UnitTest_L10/UnitTest_L10.csproj --configuration ${{matrix.configuration }}

  analyze:
    needs: testing-configurations
    runs-on: ubuntu-latest
    strategy:
        matrix:
            configuration: [Debug, Release]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
            dotnet version: '7.0.x'
        
      - name: Restore dependencies
        run: |
          dotnet restore TestDrivers9/TestDrivers9.csproj
          dotnet restore UnitTest_L10/UnitTest_L10.csproj
          dotnet restore ClassMassiv8/ClassMassiv8.csproj
        
      - name: Build projects
        run: dotnet build TestDrivers9/TestDrivers9.csproj --configuration ${{ matrix.configuration }}
        
      - name: Run code analysis
        run: dotnet tool install -g dotnet-format && dotnet format TestDrivers9/TestDrivers9.csproj

  artifacts-save:
    needs: [build-debug, build-release]
    runs-on: ubuntu-latest
    strategy:
        matrix:
            configuration: [Debug, Release]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
            dotnet version: '7.0.x'
        
      - name: Restore dependencies
        run: |
          dotnet restore TestDrivers9/TestDrivers9.csproj
          dotnet restore UnitTest_L10/UnitTest_L10.csproj
          dotnet restore ClassMassiv8/ClassMassiv8.csproj
      
      - name: Publish artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.configuration }}-build-artifacts
          path: TestDrivers9/bin/${{ matrix.configuration }}