name: Sequent Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'

      - name: Restore dependencies
        run: |
          dotnet restore TestDrivers9/TestDrivers9.csproj
          dotnet restore UnitTest_L10/UnitTest_L10.csproj
          dotnet restore ClassMassiv8/ClassMassiv8.csproj
        
      - name: Build project
        run: dotnet build TestDrivers9/TestDrivers9.csproj --configuration Release

      - name: Build test project
        run: dotnet build UnitTest_L10/UnitTest_L10.csproj --configuration Release

      - name: Publish test project
        run: dotnet publish UnitTest_L10/UnitTest_L10.csproj -c Release -r win-x64 --output UnitTest_L10/bin/Release/net7.0/win-x64

  testing-configuration:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
            dotnet-version: '7.0.x'
      
      - name: Setup coverlet
        run: dotnet tool install --global coverlet.console

      - name: Restore dependencies
        run: |
          dotnet restore TestDrivers9/TestDrivers9.csproj
          dotnet restore UnitTest_L10/UnitTest_L10.csproj
          dotnet restore ClassMassiv8/ClassMassiv8.csproj

      - name: Run tests with coverage and generate report
        run: coverlet UnitTest_L10/bin/Release/net7.0/win-x64/UnitTest_L10.dll --target "dotnet" --targetargs "test UnitTest_L10/UnitTest_L10.csproj --no-build --configuration Release" --format cobertura --output coverage.xml

  artifacts-save-documents:
    needs: testing-configuration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
            dotnet-version: '7.0.x'
        
      - name: Restore dependencies
        run: |
          dotnet restore TestDrivers9/TestDrivers9.csproj
          dotnet restore UnitTest_L10/UnitTest_L10.csproj
          dotnet restore ClassMassiv8/ClassMassiv8.csproj

      - name: Publish artifacts
        uses: actions/upload-artifact@v3
        with:
          name: release-build-artifacts
          path: coverage.xml